# Tests for Analyze Attribute Plan

# 1. Single sampling plan
#################################################################################################################
# 1.1 Test for plan table - generated by default
test_that("Analyze attribute plan single - plan table match", {
  options <- jaspTools::analysisOptions("AnalyzeAttributePlan")
  options$lotSizeSingle <- 500
  options$sampleSizeSingle <- 250
  options$acceptNumberSingle <- 10
  options$rejectNumberSingle <- 11
  options$pd_lowerSingle <- 0
  options$pd_upperSingle <- 1
  options$pd_stepSingle <- 0.05
  options$distributionSingle <- "binom"
  
  # There has to be a way to avoid this. Somehow the default values of the options are not being read during testing.
  options$assessPlanSingle <- FALSE
  options$showSummarySingle <- FALSE
  options$showOCCurveSingle <- FALSE
  options$showAOQCurveSingle <- FALSE
  options$showATICurveSingle <- FALSE
  
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  plan_table <- results[["results"]][["singleContainer"]][["collection"]][["singleContainer_plan_table"]][["data"]]
  jaspTools::expect_equal_tables(plan_table, list("Sample size", 250, "Acceptance number", 10))
})
#################################################################################################################

# 1.2 Test for assess table
test_that("Analyze attribute plan single - assess table match", {
  options <- jaspTools::analysisOptions("AnalyzeAttributePlan")
  options$lotSizeSingle <- 100
  options$sampleSizeSingle <- 50
  options$acceptNumberSingle <- 2
  options$rejectNumberSingle <- 3
  options$pd_lowerSingle <- 0
  options$pd_upperSingle <- 1
  options$pd_stepSingle <- 0.5
  options$distributionSingle <- "hypergeom"
  
  options$assessPlanSingle <- TRUE
  options$pd_prpSingle <- 0.05
  options$pd_crpSingle <- 0.15
  options$pa_prpSingle <- 0.05
  options$pa_crpSingle <- 0.1
  # There has to be a way to avoid this. Somehow the default values of the options are not being read during testing.
  options$showSummarySingle <- FALSE
  options$showOCCurveSingle <- FALSE
  options$showAOQCurveSingle <- FALSE
  options$showATICurveSingle <- FALSE
  
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  assess_table <- results[["results"]][["singleContainer"]][["collection"]][["singleContainer_riskTable"]][["data"]]
  jaspTools::expect_equal_tables(assess_table, list("AQL", 0.05, 0.95, 0.5, "RQL", 0.15, 0.1, 0.002))
})
#################################################################################################################

# 1.3 Test for AOQ Curve
test_that("Analyze attribute plan single - AOQ Curve match", {
  options <- jaspTools::analysisOptions("AnalyzeAttributePlan")
  options$lotSizeSingle <- 2000
  options$sampleSizeSingle <- 200
  options$acceptNumberSingle <- 10
  options$rejectNumberSingle <- 11
  options$pd_lowerSingle <- 0.05
  options$pd_upperSingle <- 0.25
  options$pd_stepSingle <- 0.01
  
  options$showAOQCurveSingle <- TRUE
  # There has to be a way to avoid this. Somehow the default values of the options are not being read during testing.
  options$assessPlanSingle <- FALSE
  options$showSummarySingle <- FALSE
  options$showOCCurveSingle <- FALSE
  options$showATICurveSingle <- FALSE
  
  # 1. Binomial
  options$distributionSingle <- "binom"
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  plotName <- results[["results"]][["singleContainer"]][["collection"]][["singleContainer_aoqCurve"]][["data"]]
  aoqPlotBinom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(aoqPlotBinom, "aoq-curve-single-binom")
  
  # 2. Hypergeometric
  options$distributionSingle <- "hypergeom"
  options$lotSize <- 1000
  options$sampleSizeSingle <- 100
  options$pd_step <- 0.05
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  plotName <- results[["results"]][["singleContainer"]][["collection"]][["singleContainer_aoqCurve"]][["data"]]
  aoqPlotHypergeom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(aoqPlotHypergeom, "aoq-curve-single-hypergeom")

  # # 3. Poisson
  options$distributionSingle <- "poisson"
  options$lotSize <-  500 
  options$sampleSizeSingle <- 50
  options$pd_step <- 0.1
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  plotName <- results[["results"]][["singleContainer"]][["collection"]][["singleContainer_aoqCurve"]][["data"]]
  aoqPlotPoisson <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(aoqPlotPoisson, "aoq-curve-single-poisson")
})
#################################################################################################################

# 1.4 Test for ATI Curve
test_that("Analyze attribute plan single - ATI Curve match", {
  options <- jaspTools::analysisOptions("AnalyzeAttributePlan")
  options$lotSizeSingle <- 400
  options$sampleSizeSingle <- 80
  options$acceptNumberSingle <- 4
  options$rejectNumberSingle <- 5
  options$pd_lowerSingle <- 0.10
  options$pd_upperSingle <- 0.35
  options$pd_stepSingle <- 0.02
  
  options$showATICurveSingle <- TRUE
  # There has to be a way to avoid this. Somehow the default values of the options are not being read during testing.
  options$assessPlanSingle <- FALSE
  options$showSummarySingle <- FALSE
  options$showOCCurveSingle <- FALSE
  options$showAOQCurveSingle <- FALSE
  
  # 1. Binomial
  options$distributionSingle <- "binom"
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  plotName <- results[["results"]][["singleContainer"]][["collection"]][["singleContainer_atiCurve"]][["data"]]
  atiPlotBinom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotBinom, "ati-curve-single-binom")
  
  # 2. Hypergeometric
  options$distributionSingle <- "hypergeom"
  options$lotSize <- 600
  options$sampleSizeSingle <- 70
  options$pd_step <- 0.03
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  plotName <- results[["results"]][["singleContainer"]][["collection"]][["singleContainer_atiCurve"]][["data"]]
  atiPlotHypergeom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotHypergeom, "ati-curve-single-hypergeom")

  # # 3. Poisson
  options$distributionSingle <- "poisson"
  options$lotSize <- 100
  options$sampleSizeSingle <- 20
  options$pd_step <- 0.005
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  plotName <- results[["results"]][["singleContainer"]][["collection"]][["singleContainer_atiCurve"]][["data"]]
  atiPlotPoisson <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotPoisson, "ati-curve-single-poisson")
})
#################################################################################################################

# 2. Multiple sampling plan
# Todo: add legit values for testing multiple plans.
#################################################################################################################
# 2.1 Test for plan table - generated by default
test_that("Analyze attribute plan multiple - plan table match", {
  options <- jaspTools::analysisOptions("AnalyzeAttributePlan")
  options$lotSizeMult <- 500
  options$numberOfStages <- 6
  # Todo: add legit values for "stages" - the table variable
  # options$sampleSizeMult <- c(46,46,46,46,46,46)
  # options$acceptNumberMult <- c(0,1,2,3,4,6)
  # options$rejectNumberMult <- c(3,3,4,5,6,7)
  options$pd_lowerMult <- 0
  options$pd_upperMult <- 1
  options$pd_stepMult <- 0.05
  options$distributionMult <- "binom"
  
  # There has to be a way to avoid this. Somehow the default values of the options are not being read during testing.
  options$assessPlanMult <- FALSE
  options$showSummaryMult <- FALSE
  options$showOCCurveMult <- FALSE
  options$showAOQCurveMult <- FALSE
  options$showATICurveMult <- FALSE
  options$showASNCurveMult <- FALSE
  
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  plan_table <- results[["results"]][["MultContainer"]][["collection"]][["MultContainer_plan_table"]][["data"]]
  jaspTools::expect_equal_tables(plan_table, list("Sample size", 250, "Acceptance number", 10))
})

# 2.2 Test for assess table
test_that("Analyze attribute plan Mult - assess table match", {
  options <- jaspTools::analysisOptions("AnalyzeAttributePlan")
  options$lotSizeMult <- 100
  options$sampleSizeMult <- 50
  options$acceptNumberMult <- 2
  options$rejectNumberMult <- 3
  options$pd_lowerMult <- 0
  options$pd_upperMult <- 1
  options$pd_stepMult <- 0.5
  options$distributionMult <- "hypergeom"
  
  options$assessPlanMult <- TRUE
  options$pd_prpMult <- 0.05
  options$pd_crpMult <- 0.15
  options$pa_prpMult <- 0.05
  options$pa_crpMult <- 0.1
  # There has to be a way to avoid this. Somehow the default values of the options are not being read during testing.
  options$showSummaryMult <- FALSE
  options$showOCCurveMult <- FALSE
  options$showAOQCurveMult <- FALSE
  options$showATICurveMult <- FALSE
  
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  assess_table <- results[["results"]][["MultContainer"]][["collection"]][["MultContainer_riskTable"]][["data"]]
  jaspTools::expect_equal_tables(assess_table, list("AQL", 0.05, 0.95, 0.5, "RQL", 0.15, 0.1, 0.002))
})

# 2.3 Test for AOQ Curve
test_that("Analyze attribute plan Mult - AOQ Curve match", {
  options <- jaspTools::analysisOptions("AnalyzeAttributePlan")
  options$lotSizeMult <- 2000
  options$sampleSizeMult <- 200
  options$acceptNumberMult <- 10
  options$rejectNumberMult <- 11
  options$pd_lowerMult <- 0.05
  options$pd_upperMult <- 0.25
  options$pd_stepMult <- 0.01
  
  options$showAOQCurveMult <- TRUE
  # There has to be a way to avoid this. Somehow the default values of the options are not being read during testing.
  options$assessPlanMult <- FALSE
  options$showSummaryMult <- FALSE
  options$showOCCurveMult <- FALSE
  options$showATICurveMult <- FALSE
  
  # 1. Binomial
  options$distributionMult <- "binom"
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  plotName <- results[["results"]][["MultContainer"]][["collection"]][["MultContainer_aoqCurve"]][["data"]]
  aoqPlotBinom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(aoqPlotBinom, "aoq-curve-Mult-binom")
  
  # 2. Hypergeometric
  options$distributionMult <- "hypergeom"
  options$lotSize <- 1000
  options$sampleSizeMult <- 100
  options$pd_step <- 0.05
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  plotName <- results[["results"]][["MultContainer"]][["collection"]][["MultContainer_aoqCurve"]][["data"]]
  aoqPlotHypergeom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(aoqPlotHypergeom, "aoq-curve-Mult-hypergeom")

  # # 3. Poisson
  options$distributionMult <- "poisson"
  options$lotSize <-  500 
  options$sampleSizeMult <- 50
  options$pd_step <- 0.1
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  plotName <- results[["results"]][["MultContainer"]][["collection"]][["MultContainer_aoqCurve"]][["data"]]
  aoqPlotPoisson <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(aoqPlotPoisson, "aoq-curve-Mult-poisson")
})

# 2.4 Test for ATI Curve
test_that("Analyze attribute plan Mult - ATI Curve match", {
  options <- jaspTools::analysisOptions("AnalyzeAttributePlan")
  options$lotSizeMult <- 400
  options$sampleSizeMult <- 80
  options$acceptNumberMult <- 4
  options$rejectNumberMult <- 5
  options$pd_lowerMult <- 0.10
  options$pd_upperMult <- 0.35
  options$pd_stepMult <- 0.02
  
  options$showATICurveMult <- TRUE
  # There has to be a way to avoid this. Somehow the default values of the options are not being read during testing.
  options$assessPlanMult <- FALSE
  options$showSummaryMult <- FALSE
  options$showOCCurveMult <- FALSE
  options$showAOQCurveMult <- FALSE
  
  # 1. Binomial
  options$distributionMult <- "binom"
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  plotName <- results[["results"]][["MultContainer"]][["collection"]][["MultContainer_atiCurve"]][["data"]]
  atiPlotBinom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotBinom, "ati-curve-Mult-binom")
  
  # 2. Hypergeometric
  options$distributionMult <- "hypergeom"
  options$lotSize <- 600
  options$sampleSizeMult <- 70
  options$pd_step <- 0.03
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  plotName <- results[["results"]][["MultContainer"]][["collection"]][["MultContainer_atiCurve"]][["data"]]
  atiPlotHypergeom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotHypergeom, "ati-curve-Mult-hypergeom")

  # # 3. Poisson
  options$distributionMult <- "poisson"
  options$lotSize <- 100
  options$sampleSizeMult <- 20
  options$pd_step <- 0.005
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  plotName <- results[["results"]][["MultContainer"]][["collection"]][["MultContainer_atiCurve"]][["data"]]
  atiPlotPoisson <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotPoisson, "ati-curve-Mult-poisson")
})

# 2.5 Test for ASN Curve
test_that("Analyze attribute plan Mult - ATI Curve match", {
  options <- jaspTools::analysisOptions("AnalyzeAttributePlan")
  options$lotSizeMult <- 400
  options$sampleSizeMult <- 80
  options$acceptNumberMult <- 4
  options$rejectNumberMult <- 5
  options$pd_lowerMult <- 0.10
  options$pd_upperMult <- 0.35
  options$pd_stepMult <- 0.02
  
  options$showATICurveMult <- TRUE
  # There has to be a way to avoid this. Somehow the default values of the options are not being read during testing.
  options$assessPlanMult <- FALSE
  options$showSummaryMult <- FALSE
  options$showOCCurveMult <- FALSE
  options$showAOQCurveMult <- FALSE
  
  # 1. Binomial
  options$distributionMult <- "binom"
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  plotName <- results[["results"]][["MultContainer"]][["collection"]][["MultContainer_atiCurve"]][["data"]]
  atiPlotBinom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotBinom, "ati-curve-Mult-binom")
  
  # 2. Hypergeometric
  options$distributionMult <- "hypergeom"
  options$lotSize <- 600
  options$sampleSizeMult <- 70
  options$pd_step <- 0.03
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  plotName <- results[["results"]][["MultContainer"]][["collection"]][["MultContainer_atiCurve"]][["data"]]
  atiPlotHypergeom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotHypergeom, "ati-curve-Mult-hypergeom")

  # # 3. Poisson
  options$distributionMult <- "poisson"
  options$lotSize <- 100
  options$sampleSizeMult <- 20
  options$pd_step <- 0.005
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options, makeTests = TRUE)
  plotName <- results[["results"]][["MultContainer"]][["collection"]][["MultContainer_atiCurve"]][["data"]]
  atiPlotPoisson <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotPoisson, "ati-curve-Mult-poisson")
})
